server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    waitTimeInMsWhenSyncEmpty: 0
    wait-time-in-ms-when-sync-empty: 0

spring:
  application:
    name: eureka-server